title = 'My New Hugo Site'
baseURL = "http://localhost:1313"
defaultContentLanguage = "en"

[languages]

[languages.en]
languageName = "English"
weight = 1
title = "My Site"
contentDir = 'content.en'

[languages.ta]
languageName = "Tamil"
weight = 2
title = "என் தளம்"
contentDir = 'content.ta'